background {
    monitor =
    path = screenshot   # blurs your current screen as background
    blur_passes = 3
    blur_size = 7
    brightness = 0.7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(ffffff)
    inner_color = rgb(0e0e0e)
    font_color = rgb(cccccc)
    check_color = rgb(ffffff)      # while verifying
    fail_color = rgb(ff5555)       # on wrong password
    fail_text = Fuck you
    placeholder_text = <i>password</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    #text = cmd[update:1000] echo "$(date +"%H:%M")"
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    #color = rgba(76, 255, 153, 1.0)
    color = rgba(255, 255, 255, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}