[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#555555"
blue = "#5555ff"
cyan = "#55ffff"
green = "#55ff55"
magenta = "#ff55ff"
red = "#ff5555"
white = "#ffffff"
yellow = "#ffff55"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.normal]
black = "#000000"
blue = "#0000aa"
cyan = "#00aaaa"
green = "#00aa00"
magenta = "#aa00aa"
red = "#aa0000"
white = "#aaaaaa"
yellow = "#aa5500"

[colors.primary]
background = "#000000"
foreground = "#a0a0a0"

[font]
size = 9.5

[font.bold]
family = "FiraMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraMono Nerd Font"

[font.normal]
family = "FiraMono Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
#live_config_reload = true
opacity = 0.8

[window.padding]
x = 0
y = 0
